-- 0030 (WS-C) — GRANT DELETE on skill_episode/skill_eval for dse_app.
--
-- 0019 granted only SELECT, INSERT. These are OPERATIONAL tables (not a ledger):
-- the app needs to be able to clean up episodes/evaluations per tenant —
-- retention, GDPR, reprocessing — just like console_rm.cost_rollup (0027, which
-- already has DELETE). The truly immutable ledger is audit_log, where DELETE is
-- REVOKED (0001).
--
-- Found on the first real CI run (2026-07-24): the runner uses the dse_app role
-- and the teardown of the promotion tests does DELETE FROM skill_episode →
-- "permission denied for table skill_episode". It passed locally only because
-- conftest uses the superuser role dse. Additive and idempotent (GRANT).
GRANT DELETE ON skill_episode, skill_eval TO dse_app;
