{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dse.fullname" . }}-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "dse.labels" . | nindent 4 }}
    {{- include "dse.selectorLabels" (dict "component" "postgres" "Release" .Release) | nindent 4 }}
spec:
  serviceName: {{ include "dse.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "dse.selectorLabels" (dict "component" "postgres" "Release" .Release) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dse.labels" . | nindent 8 }}
        {{- include "dse.selectorLabels" (dict "component" "postgres" "Release" .Release) | nindent 8 }}
    spec:
      {{- include "dse.podDefaults" . | nindent 6 }}
      containers:
        - name: postgres
          image: {{ include "dse.image" (dict "root" $ "repository" .Values.postgres.image.repository "tag" .Values.postgres.image.tag "digest" .Values.postgres.image.digest) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- include "dse.statefulContainerSecurityContext" . | nindent 12 }}
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: {{ include "dse.postgresSecretName" . }}
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.auth.username }}"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.auth.username }}"]
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      {{- if not .Values.postgres.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.postgres.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.postgres.persistence.storageClassName }}
        storageClassName: {{ .Values.postgres.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dse.fullname" . }}-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "dse.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "dse.selectorLabels" (dict "component" "postgres" "Release" .Release) | nindent 4 }}
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
{{- end }}
