{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dse.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "dse.labels" . | nindent 4 }}
    {{- include "dse.selectorLabels" (dict "component" "redis" "Release" .Release) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dse.selectorLabels" (dict "component" "redis" "Release" .Release) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dse.labels" . | nindent 8 }}
        {{- include "dse.selectorLabels" (dict "component" "redis" "Release" .Release) | nindent 8 }}
    spec:
      {{- include "dse.podDefaults" . | nindent 6 }}
      containers:
        - name: redis
          image: {{ include "dse.image" (dict "root" $ "repository" .Values.redis.image.repository "tag" .Values.redis.image.tag "digest" .Values.redis.image.digest) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- include "dse.statefulContainerSecurityContext" . | nindent 12 }}
          ports:
            - containerPort: 6379
              name: redis
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dse.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "dse.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "dse.selectorLabels" (dict "component" "redis" "Release" .Release) | nindent 4 }}
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
{{- end }}
