"""WSE-E4-T10 — git repo of preview manifests (the "GitOps source of truth").

The BARE repo lives at `services/validation/preview_repo/preview-manifests.git`
(read-only bind mount in the `dse-wse-gitserver` nginx container, which serves
it to the k3d cluster's Argo CD over git dumb-HTTP — `dse_net` network). The
host writes straight through the filesystem (temporary clone -> commit -> push
to the path) and runs `git update-server-info` (a dumb protocol requirement)
after every push.

Creating/removing a preview IS a git operation (real GitOps): Argo CD's
ApplicationSet (git generator `previews/*`) materializes/prunes the
corresponding Application. That is why the TTL reaper also operates HERE (it
removes the directory from git) — deleting only the namespace in the cluster
would be reverted by Argo CD's selfHeal.
"""
from __future__ import annotations

import logging
import subprocess
import tempfile
from pathlib import Path

logger = logging.getLogger("dse_validation.preview.gitops")

REPO_BARE_NAME = "preview-manifests.git"


def _run(args: list[str], cwd: str | Path, timeout: int = 60) -> subprocess.CompletedProcess:
    proc = subprocess.run(args, cwd=str(cwd), capture_output=True, text=True, timeout=timeout)
    if proc.returncode != 0:
        raise RuntimeError(f"{' '.join(args)} failed (exit={proc.returncode}): {proc.stderr.strip()}")
    return proc


def bare_repo_path(repo_dir: str | Path) -> Path:
    return Path(repo_dir) / REPO_BARE_NAME


def ensure_repo(repo_dir: str | Path) -> Path:
    """Idempotent: creates the bare repo (with an empty initial commit + `main`
    branch) and leaves it servable over dumb HTTP (`update-server-info`)."""
    bare = bare_repo_path(repo_dir)
    if (bare / "HEAD").is_file():
        return bare
    bare.mkdir(parents=True, exist_ok=True)
    _run(["git", "init", "--bare", "-b", "main", "-q", str(bare)], cwd=bare.parent)
    with tempfile.TemporaryDirectory(prefix="dse-preview-init-") as tmp:
        _run(["git", "clone", "-q", str(bare), "work"], cwd=tmp)
        work = Path(tmp) / "work"
        _run(["git", "config", "user.email", "dse-validation@dse.local"], cwd=work)
        _run(["git", "config", "user.name", "DSE Validation"], cwd=work)
        _run(["git", "checkout", "-q", "-b", "main"], cwd=work)
        (work / "README.md").write_text(
            "# preview-manifests\n\nGenerated by dse_validation (WSE-E4-T10). Do not edit by hand.\n"
        )
        _run(["git", "add", "-A"], cwd=work)
        _run(["git", "commit", "-q", "-m", "init preview-manifests"], cwd=work)
        _run(["git", "push", "-q", "origin", "main"], cwd=work)
    _run(["git", "update-server-info"], cwd=bare)
    logger.info("preview gitops: bare repo initialized at %s", bare)
    return bare


def _commit_and_push(work: Path, message: str, bare: Path) -> str:
    _run(["git", "add", "-A"], cwd=work)
    status = _run(["git", "status", "--porcelain"], cwd=work)
    if not status.stdout.strip():
        sha = _run(["git", "rev-parse", "HEAD"], cwd=work).stdout.strip()
        return sha  # idempotent no-op
    _run(["git", "commit", "-q", "-m", message], cwd=work)
    _run(["git", "push", "-q", "origin", "main"], cwd=work)
    _run(["git", "update-server-info"], cwd=bare)
    return _run(["git", "rev-parse", "HEAD"], cwd=work).stdout.strip()


def write_preview_dir(repo_dir: str | Path, preview_name: str, manifests: dict[str, str]) -> str:
    """Writes/updates `previews/<preview_name>/<file>` and pushes.
    Returns the commit sha. Idempotent (identical content => no-op)."""
    bare = ensure_repo(repo_dir)
    with tempfile.TemporaryDirectory(prefix="dse-preview-push-") as tmp:
        _run(["git", "clone", "-q", "-b", "main", str(bare), "work"], cwd=tmp)
        work = Path(tmp) / "work"
        _run(["git", "config", "user.email", "dse-validation@dse.local"], cwd=work)
        _run(["git", "config", "user.name", "DSE Validation"], cwd=work)
        target = work / "previews" / preview_name
        target.mkdir(parents=True, exist_ok=True)
        for filename, content in manifests.items():
            (target / filename).write_text(content)
        return _commit_and_push(work, f"preview {preview_name}: upsert", bare)


def remove_preview_dir(repo_dir: str | Path, preview_name: str) -> str:
    """Removes `previews/<preview_name>/` (GitOps delete — the ApplicationSet
    prunes the Application and the finalizer cascades the resources).
    Idempotent."""
    bare = ensure_repo(repo_dir)
    with tempfile.TemporaryDirectory(prefix="dse-preview-rm-") as tmp:
        _run(["git", "clone", "-q", "-b", "main", str(bare), "work"], cwd=tmp)
        work = Path(tmp) / "work"
        _run(["git", "config", "user.email", "dse-validation@dse.local"], cwd=work)
        _run(["git", "config", "user.name", "DSE Validation"], cwd=work)
        target = work / "previews" / preview_name
        if target.is_dir():
            _run(["git", "rm", "-r", "-q", f"previews/{preview_name}"], cwd=work)
        return _commit_and_push(work, f"preview {preview_name}: remove (TTL/reap)", bare)


def list_preview_dirs(repo_dir: str | Path) -> list[str]:
    bare = ensure_repo(repo_dir)
    proc = subprocess.run(
        ["git", "ls-tree", "--name-only", "main", "previews/"],
        cwd=str(bare), capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return []
    return [line.split("/", 1)[1] for line in proc.stdout.strip().splitlines() if "/" in line]
